### Workflow
#
# 1. Run `make update` to pull in updates from afar
# 2. Have a look (heh heh) at the inaccessible file: `../../../../../../fit.log`
# 2. View the `../../build/../build/action0.txt` file.
# 3. View the `../../build/action1.txt` file.
# 4. View the `../../build/action2.txt` file.
# 3. Get into the script: `./../../build/elf-script.py` (it's so awesome!)
# 3. Have a gander at the `./../../build/balrog-script.py` (it's terrible to behold)
# 5. Run the script `./../orc-script.py?cgi-input-py=degrassi` (the "orc" script)
# 5. Now run the OTHER "orc" script: `./../../build/orc-script.py` (it's a little gentler than the first)
# 5. Run the python version of the hobbit script: `./../../build/hobbit-script.py?cgi-input-py=degrassi`.
# 5. Run the bash version of the hobbit script: `./../../build/hobbit-script.sh?foo=barzork`.
# 6. Look in the `../../build/` directory.
# 5. Read the news at [CBC News](https://www.cbc.ca/news)
# 6. Now that you've had some time to reflect on the state of the world, commit your code using `git commit` and all will be well.
# 7. If you're really confident you might even want to `git push` your code to the remote repo!
# 6. Don't forget to clean up by running `make clean`


.PHONY: clean update scripts

update: ../../build/../build/action0.txt ../../build/action1.txt ../../build/action2.txt scripts

scripts: ../../build/elf-script.py ../../build/balrog-script.py ../../build/hobbit-script.py ../../build/hobbit-script.sh ../orc-script.py ../../build/orc-script.py

../../build/../build/action0.txt: | ../../build
	echo "sleeping for 20 seconds ..."
	../countdown 20
	date > ../../build/../build/action0.txt

../../build/action1.txt: ../../build/../build/action0.txt | ../../build
	date > ../../build/action1.txt

../../build/action2.txt: ../../build/action1.txt | ../../build
	date > ../../build/action2.txt

../../build/index.html: | ../../build
	echo "<html><h1>Hello!</h1></html>" > ../../build/index.html

../orc-script.py:
	chmod u+x ../orc-script.py

../../build/orc-script.py: ../orc-script.py | ../../build
	cp -p ../orc-script.py ../../build/
	sed 's/CGI Revision/CHMIGI Revision/' < ../../build/orc-script.py > orc.tmp
	mv -f orc.tmp ../../build/orc-script.py
	chmod u+x ../../build/orc-script.py

../../build/hobbit-script.py: ../hobbit-script.py | ../../build
	cp ../hobbit-script.py ../../build/
	chmod u+x ../../build/hobbit-script.py

../../build/elf-script.py: ../elf-script.py | ../../build
	cp ../elf-script.py ../../build/
	chmod u+x ../../build/elf-script.py

../../build/balrog-script.py: ../balrog-script.py | ../../build
	cp ../balrog-script.py ../../build/
	chmod u+x ../../build/balrog-script.py

../../build/hobbit-script.sh: ../hobbit-script.sh | ../../build
	cp ../hobbit-script.sh ../../build/
	chmod u+x ../../build/hobbit-script.sh

../../build:
	mkdir -p $@

clean:
	rm -Rf build
